//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 bet.rc 使用
//
#define IDR_RT_MANIFEST                 1
#define IDD_BET_DIALOG                  102
#define IDD_CUT_INPUT_DIALOG            103
#define IDD_BET_TAB_DIALOG              104
#define IDD_CONFIG_DIALOG               105
#define IDR_ACCELERATOR                 106
#define IDI_BET                         107
#define IDR_MAINFRAME                   128
#define IDI_RESET                       129
#define IDI_CLEAR                       130
#define IDI_TICK                        131
#define IDI_CALCULATOR                  132
#define IDI_SETTINGS                    133
#define IDC_SETTINGS_BUTTON             1000
#define IDC_BET_TAB                     1001
#define IDC_TAB_NAME_EDIT               1002
#define IDC_ADD_TAB_BUTTON              1003
#define IDC_CUT_EDIT                    1004
#define IDC_CUT_TEXT                    1005
#define IDC_HAVE_CLOSING_CHECK          1006
#define IDC_TOTAL_INVEST_TEXT           1007
#define IDC_L_CURRENT_PROFIT_TEXT       1008
#define IDC_R_CURRENT_PROFIT_TEXT       1009
#define IDC_L_BET_LIST                  1010
#define IDC_R_BET_LIST                  1011
#define IDC_L_BANKER_SELECTOR           1012
#define IDC_L_BET_SELECTOR              1013
#define IDC_R_BANKER_SELECTOR           1014
#define IDC_R_BET_SELECTOR              1015
#define IDC_BALANCE_AIM_BANKER_SELECTOR 1016
#define IDC_BALANCE_AIM_BET_SELECTOR    1017
#define IDC_L_AIM_BANKER_SELECTOR       1018
#define IDC_L_AIM_BET_SELECTOR          1019
#define IDC_R_AIM_BANKER_SELECTOR       1020
#define IDC_R_AIM_BET_SELECTOR          1021
#define IDC_L_BANKER_ODDS_EDIT          1022
#define IDC_L_BET_ODDS_EDIT             1023
#define IDC_R_BANKER_ODDS_EDIT          1024
#define IDC_R_BET_ODDS_EDIT             1025
#define IDC_BALANCE_AIM_BANKER_ODDS_EDIT 1026
#define IDC_BALANCE_AIM_BET_ODDS_EDIT   1027
#define IDC_L_AIM_BANKER_ODDS_EDIT      1028
#define IDC_L_AIM_BET_ODDS_EDIT         1029
#define IDC_R_AIM_BANKER_ODDS_EDIT      1030
#define IDC_R_AIM_BET_ODDS_EDIT         1031
#define IDC_L_BANKER_ODDS_SPIN          1032
#define IDC_L_BET_ODDS_SPIN             1033
#define IDC_R_BANKER_ODDS_SPIN          1034
#define IDC_R_BET_ODDS_SPIN             1035
#define IDC_BALANCE_AIM_BANKER_ODDS_SPIN 1036
#define IDC_BALANCE_AIM_BET_ODDS_SPIN   1037
#define IDC_L_AIM_BANKER_ODDS_SPIN      1038
#define IDC_L_AIM_BET_ODDS_SPIN         1039
#define IDC_R_AIM_BANKER_ODDS_SPIN      1040
#define IDC_R_AIM_BET_ODDS_SPIN         1041
#define IDC_L_AMOUNT_EDIT               1042
#define IDC_R_AMOUNT_EDIT               1043
#define IDC_L_ADD_AMOUNT_BUTTON1        1044
#define IDC_L_ADD_AMOUNT_BUTTON2        1045
#define IDC_L_ADD_AMOUNT_BUTTON3        1046
#define IDC_L_ADD_AMOUNT_BUTTON4        1047
#define IDC_R_ADD_AMOUNT_BUTTON1        1048
#define IDC_R_ADD_AMOUNT_BUTTON2        1049
#define IDC_R_ADD_AMOUNT_BUTTON3        1050
#define IDC_R_ADD_AMOUNT_BUTTON4        1051
#define IDC_L_ADD_BUTTON                1052
#define IDC_R_ADD_BUTTON                1053
#define IDC_CHANGE_BOUGHT_EDIT          1054
#define IDC_MOVE_SPIN                   1055
#define IDC_ALL_BOUGHT_BUTTON           1056
#define IDC_RESET_BUTTON                1057
#define IDC_BALANCE_RESULT_LIST         1058
#define IDC_BALANCE_CONFIRM_BUTTON      1059
#define IDC_INITIAL_AMOUNT_EDIT         1060
#define IDC_REMAINING_AMOUNT_TEXT       1061
#define IDC_L_WIN_PROB_SIDE_SELECTOR    1062
#define IDC_R_WIN_PROB_SIDE_SELECTOR    1063
#define IDC_WIN_PROB_EDIT               1064
#define IDC_WIN_PROB_ERROR_EDIT         1065
#define IDC_L_RECOMMEND_BANKER_ODDS_TEXT 1066
#define IDC_L_MIN_BANKER_ODDS_TEXT      1067
#define IDC_L_RECOMMEND_BET_ODDS_TEXT   1068
#define IDC_L_MIN_BET_ODDS_TEXT         1069
#define IDC_R_RECOMMEND_BANKER_ODDS_TEXT 1070
#define IDC_R_MIN_BANKER_ODDS_TEXT      1071
#define IDC_R_RECOMMEND_BET_ODDS_TEXT   1072
#define IDC_R_MIN_BET_ODDS_TEXT         1073
#define IDC_L_RESULT_LIST               1074
#define IDC_R_RESULT_LIST               1075
#define IDC_L_CONFIRM_BUTTON            1076
#define IDC_R_CONFIRM_BUTTON            1077
#define IDC_DEF_CUT_COMBO               1078
#define IDC_DEF_CUT_EDIT                1079
#define IDC_DEF_CLOSING_CHECK           1080
#define IDC_FAST_ADDED_AMOUNT_EDIT1     1081
#define IDC_FAST_ADDED_AMOUNT_EDIT2     1082
#define IDC_FAST_ADDED_AMOUNT_EDIT3     1083
#define IDC_FAST_ADDED_AMOUNT_EDIT4     1084
#define IDC_DEF_PROB_ERROR_EDIT         1085
#define IDC_WIN_PROB_CALCULATOR_BUTTON  1086
#define ID_CONFIRM                      32771
#define ID_CANCEL                       32772
#define ID_DELETE                       32773
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1087
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
